### ISSUE TITLE
[429 / M_LIMIT_EXCEEDED] Too Many Requests on multiple integration tests

### ISSUE THREAD

**Issue by bitfriend** [acterglobal/a3#202]
There are several tests in `effektio-test` directory.
When `emoji_verification` test or `news` test is enabled, `typing_notification` test is not working with getting the `[429 / M_LIMIT_EXCEEDED] Too Many Requests` error.
I must disable some pervious tests, before I can test new test.
I guess frequent usage of registered accounts of synapse server has some problem.
When performing `typing_notification` test, should I make new account to synapse server?

**Comment by clmnin** [comment]
You can override ratelimiting for users using the admin API

```
POST /_synapse/admin/v1/users/<user_id>/override_ratelimit
```

[Link](https://matrix-org.github.io/synapse/latest/admin_api/user_admin_api.html#override-ratelimiting-for-users) to the doc

**Comment by bitfriend** [comment]
This is my config.
As you see, `per_second` is set to `1000`.
I don't think it is low number.
```
# Configuration file for Synapse.
#
# This is a YAML file: see [1] for a quick introduction. Note in particular
# that *indentation is important*: all the elements of a list or dictionary
# should have the same indentation.
#
# [1] https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html
#
# For more information on how to configure Synapse, including a complete accounting of
# each option, go to docs/usage/configuration/config_documentation.md or
# https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html
#
# This is set in /etc/matrix-synapse/conf.d/server_name.yaml for Debian installations.
# server_name: "SERVERNAME"
pid_file: "/var/run/matrix-synapse.pid"
listeners:
  - port: 8008
    tls: false
    type: http
    x_forwarded: true
    bind_addresses: ['::1', '127.0.0.1', '192.168.101.112']
    resources:
      - names: [client, federation]
        compress: false
database:
  name: sqlite3
  args:
    database: /var/lib/matrix-synapse/homeserver.db
log_config: "/etc/matrix-synapse/log.yaml"
media_store_path: /var/lib/matrix-synapse/media
signing_key_path: "/etc/matrix-synapse/homeserver.signing.key"
trusted_key_servers:
  - server_name: "matrix.org"

allow_guest_access: true
enable_registration_without_verification: true
enable_registration: true

rc_message:
  per_second: 1000
  burst_count: 1000

rc_registration:
  per_second: 1000
  burst_count: 1000

rc_login:
  address:
    per_second: 1000
    burst_count: 1000
```
